// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform (Android, iOS, or Web).
  /// This getter automatically detects the platform and providing the corresponding configuration.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wJ1lhu_P9kDYREnlAxkOCerXRCfZ7As',
    appId: '1:79127168151:android:4ebc1b9da15367bf8295d2',
    messagingSenderId: '79127168151',
    projectId: 'koneksocmed',
    storageBucket: 'koneksocmed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-94XjDlVyhFK5Vvru_jfoYNbtx1kfkM',
    appId: '1:79127168151:ios:17ee6aaeebee7ea28295d2',
    messagingSenderId: '79127168151',
    projectId: 'koneksocmed',
    storageBucket: 'koneksocmed.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPhvipvXmnmy090sbsw-DAw3MonTChmo',
    appId: '1:79127168151:web:b4603d94641947bf8295d2',
    messagingSenderId: '79127168151',
    projectId: 'koneksocmed',
    authDomain: 'koneksocmed.firebaseapp.com',
    storageBucket: 'koneksocmed.firebasestorage.app',
  );

}