import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations instance = AppLocalizations._();
  AppLocalizations._();

  String _languageCode = 'en';
  String get languageCode => _languageCode;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _languageCode = prefs.getString('pref_language_code') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    _languageCode = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('pref_language_code', code);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_languageCode]?[key] 
        ?? _translations['en']?[key] 
        ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // Nav
      'nav_home': 'Home',
      'nav_reels': 'Reels',
      'nav_messages': 'Messages',
      'nav_me': 'Me',
      // Messages
      'msg_title': 'Messages',
      'msg_typing': 'typing...',
      'msg_no_messages': 'No messages yet',
      'msg_start_chatting': 'Start chatting with your Kakonek!',
      'msg_please_login': 'Please log in',
      'msg_new': 'New Message',
      'msg_search_friends': 'Search friends...',
      // Feed
      'feed_friends': 'Friends',
      'feed_discover': 'Discover',
      'feed_whats_on_mind': "What's on your mind?",
      'feed_your_story': 'Your Story',
      'feed_explore_discover': 'Explore Discover',
      // Create Post
      'post_create_title': 'Create Post',
      'reel_upload_title': 'Upload Reel',
      'post_who_can_see': 'Who can see this?',
      'post_public': 'Public',
      'post_public_desc': 'Everyone on Konek can see this',
      'post_kakonek': 'Kakonek',
      'post_kakonek_desc': 'Only your mutual friends can see this',
      'post_private': 'Private',
      'post_private_desc': 'Only you can see this',
      'post_hint_text': "What's on your mind?",
      'reel_hint_text': 'Add a caption... #hashtags',
      'mood_hint_text': "Share more about how you're feeling...",
      'mood_question': 'How are you feeling?',
      'mood_expired_desc': 'Expires in 24 hours',
      'post_button': 'Post',
      // Profile
      'profile_joined': 'Joined',
      'profile_posts': 'Posts',
      'profile_reels': 'Reels',
      'profile_kakonek': 'Kakonek',
      'profile_edit_profile': 'Edit Profile',
      'profile_add_kakonek': 'Add Kakonek',
      'profile_message': 'Message',
      'profile_no_posts': 'No posts yet',
      'profile_error_posts': 'Error loading posts',
      'profile_reposts': 'Reposts',
      'profile_saved': 'Saved',
      'profile_private': 'Private',
      'profile_joined_recently': 'Joined recently',
      'profile_no_kakonek': 'No Kakonek yet',
      // Drawer
      'drawer_profile': 'Profile',
      'drawer_saved_posts': 'Saved Posts',
      'drawer_kakonek_center': 'Kakonek Center',
      'drawer_settings': 'Settings',
      'drawer_report_problem': 'Report a Problem',
      'drawer_logout': 'Logout',
      'drawer_confirm_logout_title': 'Confirm Logout',
      'drawer_confirm_logout_msg': 'Are you sure you want to log out of your account?',
      'drawer_save_account': 'Save account on this device',
      'drawer_account_saved_msg': 'Your account is saved on this device.',
      'drawer_profile_photo': 'Profile Photo',
      'drawer_upload_gallery': 'Upload from Gallery',
      'drawer_remove_photo': 'Remove Photo',
      'drawer_edit_profile': 'Edit Profile',
      'drawer_display_name': 'Display Name',
      'drawer_username': 'Username',
      'drawer_bio': 'Bio',
      'drawer_save_changes': 'Save Changes',
      'drawer_profile_updated': 'Profile updated!',
      'drawer_profile_update_failed': 'Failed to update',
      'drawer_photo_updated': 'Profile picture updated',
      'drawer_photo_removed': 'Profile picture removed',
      // Settings
      'settings_title': 'Settings',
      'settings_section_preferences': 'Preferences',
      'settings_notifications': 'Notifications',
      'settings_notifications_desc': 'Push notifications & sounds',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_mode_desc': 'Dark theme for the app',
      'settings_language': 'Language',
      'settings_select_language': 'Select Language',
      'settings_section_account': 'Account',
      'settings_edit_profile': 'Edit Profile',
      'settings_security': 'Security',
      'settings_change_password': 'Change your password',
      'settings_section_legal': 'Legal',
      'settings_terms': 'Terms of Service',
      'settings_privacy': 'Privacy Policy',
      'settings_delete_account': 'Delete Account',
      'settings_delete_account_title': 'Delete Account?',
      'settings_delete_account_msg': 'This action is permanent and cannot be undone.',
      'settings_change_password_title': 'Change Password',
      'settings_current_password': 'Current Password',
      'settings_new_password': 'New Password',
      'settings_confirm_new_password': 'Confirm New Password',
      'settings_update_password_button': 'Update Password',
      'settings_password_updated': 'Password updated successfully!',
      'settings_fields_required': 'All fields are required.',
      'settings_password_too_short': 'New password must be at least 6 characters.',
      'settings_passwords_mismatch': 'Passwords do not match.',
      'settings_tap_to_update_photo': 'Tap to update photo',
      'settings_profile_updated_success': 'Profile updated successfully!',
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',
      'repost_button': 'Repost',
      'post_success': 'Posted successfully!',
      'mood_success': 'Mood shared!',
      'reel_video_ready': 'Video ready to upload as Reel',
      'reel_uploaded_success': 'Reel uploaded! 🎉',
      'post_too_large_title': 'Image Too Large',
      'reel_too_large_title': 'Video Too Large',
      'post_too_large_desc': 'Your image exceeds the 700KB limit.',
      'reel_too_large_desc': 'Your video exceeds the 700KB limit.',
      // Reels
      'reels_kakonek': 'Kakonek',
      'reels_para_sa_imo': 'Para sa Imo',
      'reels_empty_kakonek': 'No reels from your Kakonek yet',
      'reels_empty_public': 'No public reels available',
      'reels_loading': 'Loading video...',
      'reels_uploading': 'Uploading reel...',
      'reels_uploaded': 'Reel uploaded! 🎉',
      'reels_upload_failed': 'Upload failed',
      'reels_save': 'Save',
      'reels_more': 'More',
      'reels_not_interested': 'Not interested',
      'reels_hide_reel': 'Hide this reel',
      'reels_delete_confirm': 'Delete Reel?',
      'reels_delete_message': 'This reel will be permanently deleted.',
      'feed_no_posts': "Your Kakonek's posts will appear here",
      'feed_no_posts_found': 'No posts found',
      'feed_search_people': 'Search people...',
      // Post actions
      'post_like': 'Like',
      'post_comment': 'Comment',
      'post_repost': 'Repost',
      'post_save': 'Save',
      'post_saved': 'Post saved!',
      'post_unsaved': 'Post unsaved',
      'post_reposted': 'Reposted! 🎉 check your profile',
      'post_repost_removed': 'Repost removed',
      'post_deleted': 'Post deleted',
      'post_hidden': "Post hidden. You won't see this post again.",
      'post_about_account': 'About this account',
      'post_delete': 'Delete Post',
      'post_hide': 'Hide Post',
      'post_report': 'Report Post',
      'post_delete_confirm': 'Delete Post?',
      'post_delete_message': 'Are you sure you want to delete this post? This action cannot be undone.',
      'post_view_comments': 'View all',
      'post_top_comments': 'Top Comments',
      'post_see_translation': 'See translation',
      'post_translated': 'Translated',
      'post_show_original': 'Show original',
      'post_on': 'on',
      // Comments
      'comment_no_comments': 'No comments yet. Start the conversation!',
      'comment_hide_replies': 'Hide replies',
      'comment_view_replies': 'View',
      'comment_replies': 'replies',
      'comment_add': 'Add a comment...',
      'comment_reply': 'Post your reply...',
      'comment_post': 'Post',
      'comment_delete': 'Delete Comment',
      'comment_reply_label': 'Reply',
      'comment_like': 'Like',
      // Login
      'login_title': 'KONEK',
      'login_saved_account': 'Continue as saved account',
      'login_or_sign_in': '— or sign in —',
      'login_username_hint': '@username or email',
      'login_password_hint': 'Password',
      'login_button': 'Log In',
      'login_forgot': 'Forgot password?',
      'login_create': 'Create account',
      'login_google': 'Continue with Google',
      'login_google_button': 'Continue with Google',
      'login_remove_account': 'Remove account?',
      'login_remove_confirm': 'Remove saved account?',
      'login_remove_message': 'Are you sure you want to remove the saved account for',
      'login_enter_password': 'Enter Password',
      'login_continue_saved': 'Continue as saved account',
      'login_email_hint': 'Enter your email',
      'login_fill_fields': 'Please fill all fields',
      'login_or_sign_in': 'or sign in',
      'login_forgot_password': 'Forgot password?',
      'login_create_account': 'Create account',
      'remove': 'Remove',
      // Sign up
      'signup_title': 'Create Account',
      'signup_subtitle': 'Join the KONEK community',
      'signup_name': 'Full Name',
      'signup_email': 'Email Address',
      'signup_password': 'Password',
      'signup_confirm': 'Confirm Password',
      'signup_button': 'Sign Up',
      'signup_success': 'Account created successfully! Please log in.',
      'signup_password_mismatch': 'Passwords do not match',
      'signup_password_short': 'Password must be at least 6 characters',
      'signup_name_hint': 'Enter your full name',
      'signup_email_hint': 'Enter your email',
      'signup_confirm_password_hint': 'Confirm your password',
      // Settings
      'settings_title': 'Settings',
      'settings_language': 'Language',
      'settings_select_language': 'Select Language',
      'settings_dark_mode': 'Dark Mode',
      'settings_notifications': 'Notifications',
      'settings_logout': 'Log Out',
      'settings_save_account': 'Save account on this device',
      // Menu / Profile
      'menu_kakonek_center': 'Kakonek Center',
      'menu_settings': 'Settings',
      'menu_report_problem': 'Report a Problem',
      'menu_switch_account': 'Switch Account',
      'menu_no_other_accounts': 'No other accounts to switch to',
      'menu_switching_account': 'Switching account...',
      'menu_logout_confirm': 'Confirm Logout',
      'menu_logout_message': 'Are you sure you want to log out?',
      'menu_save_account': 'Save account on this device',
      'menu_logout': 'Log Out',
      // General
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'ok': 'OK',
      'error_try_again': 'Something went wrong. Please try again.',
      'translating': 'Translating...',
      'time_just_now': 'Just now',
      'time_m_ago': 'm ago',
      'time_h_ago': 'h ago',
      'time_d_ago': 'd ago',
      'time_minutes_ago': 'm ago',
      'time_hours_ago': 'h ago',
      'time_days_ago': 'd ago',
      // Notifications
      'notifications_title': 'Notifications',
      'notifications_mark_all_read': 'Mark all as read',
      'notifications_none': 'No notifications yet',
      'notifications_accept': 'Accept',
      'notifications_decline': 'Decline',
      // Feed additional
      'feed_no_discover_posts': 'No posts found in Discover',
      'feed_no_posts': "Your Kakonek's posts will appear here",
      // General
      'not_logged_in': 'Not logged in',
      'phone_number': 'Mobile Number',
      'email_label': 'Email Address',
      // Kakonek Center
      'kakonek_center_title': 'Kakonek Center',
      'kakonek_search_hint': 'Search Kakonek...',
      'kakonek_tab_my': 'My Kakonek',
      'kakonek_tab_requests': 'Requests',
      'kakonek_tab_suggestions': 'Suggestions',
      'kakonek_no_kakonek': 'No Kakonek yet',
      'kakonek_no_friends_found': 'No friends found',
      'kakonek_start_connecting': 'Start connecting with others',
      'kakonek_try_different_search': 'Try a different search',
      'kakonek_no_requests': 'No pending requests',
      'kakonek_invitations_appear': 'Invitations appear here',
      'kakonek_no_suggestions': 'No suggestions',
      'kakonek_no_results': 'No results',
      'kakonek_is_kakonek': 'Kakonek',
      'kakonek_pending': 'Pending',
      'kakonek_add': 'Add',
      'kakonek_request_sent': 'Request sent to',
      'kakonek_request_accepted': 'Kakonek request accepted!',
      'kakonek_request_declined': 'Request declined',
      'kakonek_view_profile': 'View Profile',
      'kakonek_unfriend': 'Unfriend',
      'kakonek_unfriend_confirm': 'Are you sure you want to remove this connection?',
      // Saved Posts
      'saved_title': 'Saved',
      'saved_tab_posts': 'Posts',
      'saved_tab_reels': 'Reels',
      'saved_tab_reposts': 'Reposts',
      'saved_tab_tagged': 'Tagged',
      'saved_no_posts': 'No saved posts yet',
      'saved_no_reels': 'No saved reels yet',
      'saved_no_reposts': 'No saved reposts',
      'saved_tagged': "Posts where you're tagged",
    },
    'fil': {
      // Nav
      'nav_home': 'Home',
      'nav_reels': 'Reels',
      'nav_messages': 'Mga Mensahe',
      'nav_me': 'Ako',
      // Messages
      'msg_title': 'Mga Mensahe',
      'msg_typing': 'nagsusulat...',
      'msg_no_messages': 'Wala pang mga mensahe',
      'msg_start_chatting': 'Simulan ang pakikipag-chat sa iyong Kakonek!',
      'msg_please_login': 'Mangyaring mag-log in',
      'msg_new': 'Bagong Mensahe',
      'msg_search_friends': 'Maghanap ng mga kaibigan...',
      // Feed
      'feed_friends': 'Mga Kaibigan',
      'feed_discover': 'Tuklasin',
      'feed_whats_on_mind': 'Ano ang naiisip mo?',
      'feed_your_story': 'Iyong Kwento',
      'feed_explore_discover': 'I-explore ang Tuklasin',
      // Create Post
      'post_create_title': 'Gumawa ng Post',
      'reel_upload_title': 'I-upload ang Reel',
      'post_who_can_see': 'Sino ang makakakita nito?',
      'post_public': 'Public',
      'post_public_desc': 'Makikita ito ng lahat sa Konek',
      'post_kakonek': 'Kakonek',
      'post_kakonek_desc': 'Makikita lang ito ng iyong mga mutual friend',
      'post_private': 'Private',
      'post_private_desc': 'Ikaw lang ang makakakita nito',
      'post_hint_text': 'Ano ang naiisip mo?',
      'reel_hint_text': 'Magdagdag ng caption... #hashtags',
      'mood_hint_text': 'Magbahagi pa tungkol sa iyong nararamdaman...',
      'mood_question': 'Ano ang nararamdaman mo?',
      'mood_expired_desc': 'Mag-e-expire sa loob ng 24 oras',
      'post_button': 'I-post',
      // Profile
      'profile_joined': 'Sumali noong',
      'profile_posts': 'Mga Post',
      'profile_reels': 'Mga Reel',
      'profile_kakonek': 'Kakonek',
      'profile_edit_profile': 'I-edit ang Profile',
      'profile_add_kakonek': 'Magdagdag ng Kakonek',
      'profile_message': 'Mensahe',
      'profile_no_posts': 'Wala pang mga post',
      'profile_error_posts': 'Error sa pag-load ng mga post',
      'profile_reposts': 'Mga Repost',
      'profile_saved': 'Naka-save',
      'profile_private': 'Private',
      'profile_joined_recently': 'Kakasali lang',
      'profile_no_kakonek': 'Wala pang Kakonek',
      // Drawer
      'drawer_profile': 'Profile',
      'drawer_saved_posts': 'Mga Naka-save na Post',
      'drawer_kakonek_center': 'Kakonek Center',
      'drawer_settings': 'Mga Setting',
      'drawer_report_problem': 'Mag-ulat ng Problema',
      'drawer_logout': 'Mag-log out',
      'drawer_confirm_logout_title': 'Kumpirmahin ang Pag-log out',
      'drawer_confirm_logout_msg': 'Sigurado ka bang gusto mong mag-log out sa iyong account?',
      'drawer_save_account': 'I-save ang account sa device na ito',
      'drawer_account_saved_msg': 'Naka-save ang iyong account sa device na ito.',
      'drawer_profile_photo': 'Larawan sa Profile',
      'drawer_upload_gallery': 'I-upload mula sa Gallery',
      'drawer_remove_photo': 'Alisin ang Larawan',
      'drawer_edit_profile': 'I-edit ang Profile',
      'drawer_display_name': 'Pangalan sa Display',
      'drawer_username': 'Username',
      'drawer_bio': 'Bio',
      'drawer_save_changes': 'I-save ang mga Pagbabago',
      'drawer_profile_updated': 'Na-update na ang profile!',
      'drawer_profile_update_failed': 'Nabigong i-update',
      'drawer_photo_updated': 'Na-update na ang larawan sa profile',
      'drawer_photo_removed': 'Inalis na ang larawan sa profile',
      // Settings
      'settings_title': 'Mga Setting',
      'settings_section_preferences': 'Mga Kagustuhan',
      'settings_notifications': 'Mga Abiso',
      'settings_notifications_desc': 'Push notifications at mga tunog',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_mode_desc': 'Dark theme para sa app',
      'settings_language': 'Wika',
      'settings_select_language': 'Pumili ng Wika',
      'settings_section_account': 'Account',
      'settings_edit_profile': 'I-edit ang Profile',
      'settings_security': 'Seguridad',
      'settings_change_password': 'Baguhin ang iyong password',
      'settings_section_legal': 'Legal',
      'settings_terms': 'Terms of Service',
      'settings_privacy': 'Patakaran sa Privacy',
      'settings_delete_account': 'I-delete ang Account',
      'settings_delete_account_title': 'I-delete ang Account?',
      'settings_delete_account_msg': 'Ang aksyong ito ay permanenteng at hindi na maaaring bawiin.',
      'settings_change_password_title': 'Baguhin ang Password',
      'settings_current_password': 'Kasalukuyang Password',
      'settings_new_password': 'Bagong Password',
      'settings_confirm_new_password': 'Kumpirmahin ang Bagong Password',
      'settings_update_password_button': 'I-update ang Password',
      'settings_password_updated': 'Matagumpay na na-update ang password!',
      'settings_fields_required': 'Lahat ng field ay kinakailangan.',
      'settings_password_too_short': 'Ang bagong password ay dapat na hindi bababa sa 6 na character.',
      'settings_passwords_mismatch': 'Hindi tumutugma ang mga password.',
      'settings_tap_to_update_photo': 'I-tap para i-update ang larawan',
      'settings_profile_updated_success': 'Matagumpay na na-update ang profile!',
      'month_jan': 'Ene',
      'month_feb': 'Peb',
      'month_mar': 'Mar',
      'month_apr': 'Abr',
      'month_may': 'May',
      'month_jun': 'Hun',
      'month_jul': 'Hul',
      'month_aug': 'Ago',
      'month_sep': 'Set',
      'month_oct': 'Okt',
      'month_nov': 'Nob',
      'month_dec': 'Dis',
      'repost_button': 'I-repost',
      'post_success': 'Matagumpay na nai-post!',
      'mood_success': 'Naibahagi ang mood!',
      'reel_video_ready': 'Handa nang i-upload ang video bilang Reel',
      'reel_uploaded_success': 'Na-upload na ang Reel! 🎉',
      'post_too_large_title': 'Masyadong Malaki ang Larawan',
      'reel_too_large_title': 'Masyadong Malaki ang Video',
      'post_too_large_desc': 'Ang iyong larawan ay lumampas sa 700KB limit.',
      'reel_too_large_desc': 'Ang iyong video ay lumampas sa 700KB limit.',
      // Reels
      'reels_kakonek': 'Kakonek',
      'reels_para_sa_imo': 'Para sa Iyo',
      'reels_empty_kakonek': 'Wala pang mga reel mula sa iyong Kakonek',
      'reels_empty_public': 'Walang available na pampublikong reel',
      'reels_loading': 'Naglo-load ng video...',
      'reels_uploading': 'Nag-a-upload ng reel...',
      'reels_uploaded': 'Na-upload na ang Reel! 🎉',
      'reels_upload_failed': 'Nabigo ang pag-upload',
      'reels_save': 'I-save',
      'reels_more': 'Higit pa',
      'reels_not_interested': 'Hindi interesado',
      'reels_hide_reel': 'Itago ang reel na ito',
      'reels_delete_confirm': 'Burahin ang Reel?',
      'reels_delete_message': 'Ang reel na ito ay permanenteng mabubura.',
      'feed_no_posts': 'Dito makikita ang mga post ng iyong Kakonek',
      'feed_no_posts_found': 'Walang nahanap na post',
      'feed_search_people': 'Maghanap ng tao...',
      // Post actions
      'post_like': 'Gusto',
      'post_comment': 'Komento',
      'post_repost': 'I-repost',
      'post_save': 'I-save',
      'post_saved': 'Na-save ang post!',
      'post_unsaved': 'Hindi na-save ang post',
      'post_reposted': 'Na-repost! 🎉 tingnan ang iyong profile',
      'post_repost_removed': 'Tinanggal ang repost',
      'post_deleted': 'Tinanggal ang post',
      'post_hidden': 'Nakatago ang post. Hindi mo na ito makikita.',
      'post_about_account': 'Tungkol sa account na ito',
      'post_delete': 'Tanggalin ang Post',
      'post_hide': 'Itago ang Post',
      'post_report': 'Iulat ang Post',
      'post_delete_confirm': 'Tanggalin ang Post?',
      'post_delete_message': 'Sigurado ka bang gusto mong tanggalin ang post na ito?',
      'post_view_comments': 'Tingnan lahat',
      'post_top_comments': 'Mga Nangungunang Komento',
      'post_see_translation': 'Tingnan ang pagsasalin',
      'post_translated': 'Isinalin',
      'post_show_original': 'Ipakita ang orihinal',
      'post_on': 'sa',
      // Comments
      'comment_no_comments': 'Wala pang komento. Simulan ang usapan!',
      'comment_hide_replies': 'Itago ang mga reply',
      'comment_view_replies': 'Tingnan ang',
      'comment_replies': 'na reply',
      'comment_add': 'Magdagdag ng komento...',
      'comment_reply': 'I-post ang iyong tugon...',
      'comment_post': 'I-post',
      'comment_delete': 'Tanggalin ang Komento',
      'comment_reply_label': 'Tumugon',
      'comment_like': 'Gusto',
      // Login
      'login_title': 'KONEK',
      'login_saved_account': 'Magpatuloy bilang naka-save na account',
      'login_or_sign_in': '— o mag-sign in —',
      'login_username_hint': '@username o email',
      'login_password_hint': 'Password',
      'login_button': 'Mag-login',
      'login_forgot': 'Nakalimutan ang password?',
      'login_create': 'Gumawa ng account',
      'login_google': 'Magpatuloy gamit ang Google',
      'login_google_button': 'Magpatuloy gamit ang Google',
      'login_remove_account': 'Alisin ang account?',
      'login_remove_confirm': 'Alisin ang naka-save na account?',
      'login_remove_message': 'Sigurado ka bang gusto mong alisin ang naka-save na account para sa',
      'login_enter_password': 'Ilagay ang Password',
      'login_continue_saved': 'Magpatuloy bilang naka-save na account',
      'login_email_hint': 'Ilagay ang iyong email',
      'login_fill_fields': 'Mangyaring punan ang lahat ng field',
      'login_or_sign_in': 'o mag-sign in',
      'login_forgot_password': 'Nakalimutan ang password?',
      'login_create_account': 'Gumawa ng account',
      'remove': 'Alisin',
      // Sign up
      'signup_title': 'Gumawa ng Account',
      'signup_subtitle': 'Sumali sa komunidad ng KONEK',
      'signup_name': 'Buong Pangalan',
      'signup_email': 'Email Address',
      'signup_password': 'Password',
      'signup_confirm': 'Kumpirmahin ang Password',
      'signup_button': 'Mag-sign Up',
      'signup_success': 'Matagumpay na nagawa ang account! Mangyaring mag-login.',
      'signup_password_mismatch': 'Hindi magkatugma ang mga password',
      'signup_password_short': 'Ang password ay dapat na hindi bababa sa 6 na character',
      'signup_name_hint': 'Ilagay ang iyong buong pangalan',
      'signup_email_hint': 'Ilagay ang iyong email',
      'signup_confirm_password_hint': 'Kumpirmahin ang iyong password',
      // Settings
      'settings_title': 'Mga Setting',
      'settings_language': 'Wika',
      'settings_select_language': 'Pumili ng Wika',
      'settings_dark_mode': 'Dark Mode',
      'settings_notifications': 'Mga Abiso',
      'settings_logout': 'Mag-logout',
      'settings_save_account': 'I-save ang account sa device na ito',
      // Menu / Profile
      'menu_kakonek_center': 'Kakonek Center',
      'menu_settings': 'Mga Setting',
      'menu_report_problem': 'Mag-ulat ng Problema',
      'menu_switch_account': 'Magpalit ng Account',
      'menu_no_other_accounts': 'Walang ibang account na mapapalitan',
      'menu_switching_account': 'Nagpapalit ng account...',
      'menu_logout_confirm': 'Kumpirmahin ang Pag-logout',
      'menu_logout_message': 'Sigurado ka bang gusto mong mag-logout?',
      'menu_save_account': 'I-save ang account sa device na ito',
      'menu_logout': 'Mag-logout',
      // General
      'cancel': 'Kanselahin',
      'save': 'I-save',
      'delete': 'Tanggalin',
      'confirm': 'Kumpirmahin',
      'ok': 'OK',
      'error_try_again': 'May nangyaring mali. Subukan ulit.',
      'translating': 'Isinasalin...',
      'time_just_now': 'Ngayon lang',
      'time_m_ago': 'm ang nakalipas',
      'time_h_ago': 'h ang nakalipas',
      'time_d_ago': 'd ang nakalipas',
      'time_minutes_ago': 'm nakalipas',
      'time_hours_ago': 'h nakalipas',
      'time_days_ago': 'd nakalipas',
      // Notifications
      'notifications_title': 'Mga Abiso',
      'notifications_mark_all_read': 'Markahan lahat bilang nabasa',
      'notifications_none': 'Wala pang mga abiso',
      'notifications_accept': 'Tanggapin',
      'notifications_decline': 'Tanggihan',
      // Feed additional
      'feed_no_discover_posts': 'Walang nahanap na mga post sa Tuklasin',
      'feed_no_posts': 'Ang mga post ng iyong Kakonek ay lilitaw dito',
      // General
      'not_logged_in': 'Hindi naka-log in',
      'phone_number': 'Numero ng Telepono',
      'email_label': 'Email Address',
      // Kakonek Center
      'kakonek_center_title': 'Kakonek Center',
      'kakonek_search_hint': 'Maghanap ng Kakonek...',
      'kakonek_tab_my': 'Mga Kakonek Ko',
      'kakonek_tab_requests': 'Mga Kahilingan',
      'kakonek_tab_suggestions': 'Mga Mungkahi',
      'kakonek_no_kakonek': 'Wala pang Kakonek',
      'kakonek_no_friends_found': 'Walang nahanap na mga kaibigan',
      'kakonek_start_connecting': 'Magsimulang makipag-ugnayan sa iba',
      'kakonek_try_different_search': 'Subukang mag-search ng iba',
      'kakonek_no_requests': 'Walang mga naghihintay na kahilingan',
      'kakonek_invitations_appear': 'Ang mga imbitasyon ay lilitaw dito',
      'kakonek_no_suggestions': 'Walang mga mungkahi',
      'kakonek_no_results': 'Walang resulta',
      'kakonek_is_kakonek': 'Kakonek',
      'kakonek_pending': 'Hinihintay',
      'kakonek_add': 'Idagdag',
      'kakonek_request_sent': 'Naipadala ang kahilingan kay',
      'kakonek_request_accepted': 'Tinanggap ang Kakonek request!',
      'kakonek_request_declined': 'Tinanggihan ang kahilingan',
      'kakonek_view_profile': 'Tingnan ang Profile',
      'kakonek_unfriend': 'Tanggalin sa Kakonek',
      'kakonek_unfriend_confirm': 'Sigurado ka bang gusto mong alisin ang koneksyong ito?',
      // Saved Posts
      'saved_title': 'Naka-save',
      'saved_tab_posts': 'Mga Post',
      'saved_tab_reels': 'Mga Reel',
      'saved_tab_reposts': 'Mga Repost',
      'saved_tab_tagged': 'Na-tag ka',
      'saved_no_posts': 'Wala pang naka-save na mga post',
      'saved_no_reels': 'Wala pang naka-save na mga reel',
      'saved_no_reposts': 'Walang naka-save na mga repost',
      'saved_tagged': 'Mga post kung saan ka na-tag',
    },
    'es': {
      'nav_home': 'Inicio', 'nav_reels': 'Reels',
      'nav_messages': 'Mensajes', 'nav_me': 'Yo',
      'feed_friends': 'Amigos', 'feed_discover': 'Descubrir',
      'feed_whats_on_mind': '¿Qué estás pensando?',
      'feed_your_story': 'Tu historia',
      'feed_explore_discover': 'Explorar descubrir',
      'feed_search_people': 'Buscar personas...',
      'post_like': 'Me gusta', 'post_comment': 'Comentar',
      'post_repost': 'Repostear', 'post_save': 'Guardar',
      'post_saved': '¡Post guardado!', 'post_unsaved': 'Post no guardado',
      'post_deleted': 'Post eliminado', 'post_see_translation': 'Ver traducción',
      'post_translated': 'Traducido', 'post_show_original': 'Mostrar original',
      'post_on': 'en', 'comment_no_comments': 'Aún no hay comentarios.',
      'comment_hide_replies': 'Ocultar respuestas', 'comment_view_replies': 'Ver',
      'comment_replies': 'respuestas',
      'comment_add': 'Añadir un comentario...',
      'login_button': 'Iniciar sesión', 'login_google': 'Continuar con Google',
      'login_forgot': '¿Olvidaste tu contraseña?', 'login_create': 'Crear cuenta',
      'settings_language': 'Idioma', 'settings_logout': 'Cerrar sesión',
      'cancel': 'Cancelar', 'save': 'Guardar', 'delete': 'Eliminar',
      'translating': 'Traduciendo...',
      'menu_switch_account': 'Cambiar cuenta',
      'menu_logout': 'Cerrar sesión',
      'msg_title': 'Mensajes',
      'time_just_now': 'Ahora mismo',
      'time_m_ago': 'm hace',
      'time_h_ago': 'h hace',
      'time_d_ago': 'd hace',
    },
    'ja': {
      'nav_home': 'ホーム', 'nav_reels': 'リール',
      'nav_messages': 'メッセージ', 'nav_me': '自分',
      'feed_friends': '友達', 'feed_discover': '発見',
      'feed_whats_on_mind': '今何を考えていますか？',
      'feed_search_people': '人を検索...',
      'post_like': 'いいね', 'post_comment': 'コメント',
      'post_repost': 'リポスト', 'post_save': '保存',
      'post_saved': '投稿を保存しました！', 'post_deleted': '投稿を削除しました',
      'post_see_translation': '翻訳を見る', 'post_translated': '翻訳済み',
      'post_show_original': '元の文章を表示',
      'comment_add': 'コメントを追加...',
      'login_button': 'ログイン', 'login_google': 'Googleで続ける',
      'settings_language': '言語', 'settings_logout': 'ログアウト',
      'cancel': 'キャンセル', 'save': '保存', 'delete': '削除',
      'translating': '翻訳中...',
      'menu_switch_account': 'アカウントを切り替える',
      'menu_logout': 'ログアウト',
      'msg_title': 'メッセージ',
      'time_just_now': 'たった今',
      'time_m_ago': '分前',
      'time_h_ago': '時間前',
      'time_d_ago': '日前',
    },
    'ko': {
      'nav_home': '홈', 'nav_reels': '릴스',
      'nav_messages': '메시지', 'nav_me': '나',
      'feed_friends': '친구', 'feed_discover': '탐색',
      'feed_whats_on_mind': '무슨 생각을 하고 있나요?',
      'feed_search_people': '사람 검색...',
      'post_like': '좋아요', 'post_comment': '댓글',
      'post_repost': '리포스트', 'post_save': '저장',
      'post_saved': '게시물 저장됨!', 'post_deleted': '게시물 삭제됨',
      'post_see_translation': '번역 보기', 'post_translated': '번역됨',
      'post_show_original': '원문 보기',
      'comment_add': '댓글 추가...',
      'login_button': '로그인', 'login_google': 'Google로 계속',
      'settings_language': '언어', 'settings_logout': '로그아웃',
      'cancel': '취소', 'save': '저장', 'delete': '삭제',
      'translating': '번역 중...',
      'menu_switch_account': '계정 전환',
      'menu_logout': '로그아웃',
      'msg_title': '메시지',
      'time_just_now': '방금 전',
      'time_m_ago': '분 전',
      'time_h_ago': '시간 전',
      'time_d_ago': '일 전',
    },
    'zh': {
      'nav_home': '首页', 'nav_reels': '短视频',
      'nav_messages': '消息', 'nav_me': '我',
      'feed_friends': '朋友', 'feed_discover': '发现',
      'feed_whats_on_mind': '你在想什么？',
      'feed_search_people': '搜索人...',
      'post_like': '喜欢', 'post_comment': '评论',
      'post_repost': '转发', 'post_save': '保存',
      'post_saved': '帖子已保存！', 'post_deleted': '帖子已删除',
      'post_see_translation': '查看翻译', 'post_translated': '已翻译',
      'post_show_original': '显示原文',
      'comment_add': '添加评论...',
      'login_button': '登录', 'login_google': '使用Google继续',
      'settings_language': '语言', 'settings_logout': '退出登录',
      'cancel': '取消', 'save': '保存', 'delete': '删除',
      'translating': '翻译中...',
      'menu_switch_account': '切换账号',
      'menu_logout': '退出登录',
      'msg_title': '消息',
      'time_just_now': '刚刚',
      'time_m_ago': '分钟前',
      'time_h_ago': '小时前',
      'time_d_ago': '天前',
    },
  };
}
